sudo: false
language: python
python:
  - "3.5"
env:
  - TOXENV=py27-unittests
  - TOXENV=py33-unittests
  - TOXENV=py34-unittests
  - TOXENV=py35-unittests
install:
  - pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - codecov
