site_name: PyMdown Extensions Documentation
repo_url: https://github.com/facelessuser/pymdown-extensions
site_description: A Collection of Useful Extensions for Python Markdown
copyright: Copyright &copy; 2014 - 2017 <a href="https://github.com/facelessuser">Isaac Muse</a>
pages:
  - PyMdown Extensions: index.md
  - Installation: installation.md
  - Usage Notes: usage_notes.md
  - Extensions:
    - Arithmatex: extensions/arithmatex.md
    - B64: extensions/b64.md
    - BetterEm: extensions/betterem.md
    - Caret: extensions/caret.md
    - Critic: extensions/critic.md
    - Emoji: extensions/emoji.md
    - Extra: extensions/extra.md
    - ExtraRawHtml: extensions/extrarawhtml.md
    - Github: extensions/github.md
    - GithubEmoji: extensions/githubemoji.md
    - HeaderAnchor: extensions/headeranchor.md
    - InlineHilite: extensions/inlinehilite.md
    - MagicLink: extensions/magiclink.md
    - Mark: extensions/mark.md
    - PathConverter: extensions/pathconverter.md
    - PlainHtml: extensions/plainhtml.md
    - ProgressBar: extensions/progressbar.md
    - PyMdown: extensions/pymdown.md
    - SmartSymbols: extensions/smartsymbols.md
    - SuperFences: extensions/superfences.md
    - Tasklist: extensions/tasklist.md
    - Tilde: extensions/tilde.md
  - Miscellaneous Extras: miscellaneous_extras.md
  - Contributing &amp; Suppport: contributing.md
  - Changelog: changelog.md
  - License: license.md
theme: material
theme_dir: doc_theme
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: 
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.nl2br:
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.extra:
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      options:
        attributes:
          height: 20px
          width: 20px
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.critic:
  - pymdownx.plainhtml:
      strip_attributes: ''

extra:
  palette:
    primary: blue
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  social:
    - type: github
      link: https://github.com/facelessuser
extra_css:
  - extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.4/raphael-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.4.2/flowchart.min.js
  - extra.js
